# Generated by Django 5.2.4 on 2025-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_spotlighted',
            field=models.BooleanField(default=False, help_text='Check this to feature this article on the articles page.'),
        ),
    ]
