# Generated by Django 5.2.4 on 2025-08-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_article_is_spotlighted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(help_text='Comma-separated keywords that will trigger this answer (e.g., password, reset, change password).', max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ / Chatbot Entry',
                'verbose_name_plural': 'FAQ / Chatbot Entries',
            },
        ),
    ]
